export const SEARCH_ITEMS = [
  { id: '1', name: 'React Native', description: 'A framework for building native mobile apps using React.' },
  { id: '2', name: 'Expo', description: 'A toolchain built around React Native to help build native apps quickly.' },
  { id: '3', name: 'Redux', description: 'A state management library for JavaScript apps.' },
  { id: '4', name: 'TypeScript', description: 'A statically typed superset of JavaScript.' },
  { id: '5', name: 'Navigation', description: 'Library used to handle navigation between screens.' },
  { id: '6', name: 'AsyncStorage', description: 'Persistent key-value storage system for React Native.' },
  { id: '7', name: 'Context API', description: 'A way to share global state in React apps.' },
  { id: '8', name: 'FlatList', description: 'Component for rendering performant scrollable lists.' },
  { id: '9', name: 'Dark Mode', description: 'Theme setting for low-light environments.' },
  { id: '10', name: 'Localization', description: 'Supports multiple languages and regional settings.' },
  { id: '11', name: 'Gesture Handler', description: 'Library for handling gestures in React Native.' },
  { id: '12', name: 'Reanimated', description: 'A performant animation library for React Native.' },
  { id: '13', name: 'Styled Components', description: 'Use tagged template literals to style your apps.' },
  { id: '14', name: 'Axios', description: 'Promise-based HTTP client for API requests.' },
  { id: '15', name: 'Formik', description: 'Library for building and managing forms in React.' },
  { id: '16', name: 'Yup', description: 'Schema builder for validating form data.' },
  { id: '17', name: 'NetInfo', description: 'Check internet connectivity status.' },
  { id: '18', name: 'Vector Icons', description: 'Popular icon sets for React Native.' },
  { id: '19', name: 'React Query', description: 'Data-fetching and caching library.' },
  { id: '20', name: 'Zustand', description: 'Minimal state-management solution for React.' },
  { id: '21', name: 'Splash Screen', description: 'Initial loading screen for mobile apps.' },
  { id: '22', name: 'App Intro', description: 'Feature to show onboarding screens for users.' },
  { id: '23', name: 'Push Notifications', description: 'Send real-time alerts to users.' },
  { id: '24', name: 'Biometric Auth', description: 'Authenticate users using Face ID or Fingerprint.' },
  { id: '25', name: 'Permissions', description: 'Request and check device permissions.' },
  { id: '26', name: 'Camera', description: 'Access and use device camera features.' },
  { id: '27', name: 'Maps', description: 'Integrate interactive maps in the app.' },
  { id: '28', name: 'Deep Linking', description: 'Navigate users directly to specific app screens.' },
  { id: '29', name: 'Code Push', description: 'Deploy app updates instantly without store review.' },
  { id: '30', name: 'Firebase', description: 'Platform for backend services like auth, DB, storage.' },
];
