// src/constants/strings.js

const Strings = {
  welcome: 'welcome',
  buttonTitle: 'login',
  homeTitle: 'homeTitle',
  settingsTitle: 'settingsTitle',
  toggleTheme: 'toggleTheme',
  changeLanguage: 'changeLanguage',
  itemOne: 'Item One',
  itemTwo: 'Item Two',
  itemThree: "Item Three",
  selectedItem: "You selected",
  greetings: "Thank You",
  enterText: 'enterText',
  youTyped: 'youTyped',
  enterName: 'enterName',
  errorNameRequired: 'errorNameRequired',
  errorNameShort: 'errorNameShort',
  errorEmailRequired: 'errorEmailRequired',
  errorEmailInvalid: 'errorEmailInvalid',
  openModal: "Open Modal",
  modalTitle: "Attention",
  modalMessage: "This is a localized reusable modal.",
  close: "Close",
  nameField: 'nameField',
  emailField: 'emailField',
  profileTitle: 'profileTitle',
  counterTitle: 'counterTitle',
  submitLabel: 'submitLabel',
  nameLabel: 'nameLabel',
  emailLabel: 'emailLabel',
  save: 'Save',
  success: 'Success',
  profileUpdated: 'Profile updated successfully',
  notificationTitle: 'notificationTitle',
  noNotification: 'noNotification',
  deleteNotificationTitle: 'deleteNotificationTitle',
  deleteNotificationMessage: 'deleteNotificationMessage',
  cancel: 'cancel',
  delete: 'delete',
  whatIsThisApp: 'whatIsThisApp',
  whatIsThisAppDetail: 'whatIsThisAppDetail',
  howToChangeTheme: 'howToChangeTheme',
  howToChangeThemeDetail: 'howToChangeThemeDetail',
  languageSupport: 'languageSupport',
  languageSupportDetail: 'languageSupportDetail',
  helpScreenTitle: 'helpScreenTitle',
   searchTitle: 'searchTitle',
  searchPlaceHolder: 'searchPlaceHolder',
  loadMore: 'loadMore',
};

export default Strings;
